[build]
command = 'npm run build'
functions = 'functions'
publish = 'build'

[[redirects]]
  from = "https://netlify.pet-tracker.app/*"
  to = "https://alch-pet-tracker.herokuapp.com/:splat"
  status = 200
  force = true